### ISSUE TITLE
Don't use typeof(x).name.primary

### ISSUE THREAD

**Issue by andreasnoack** [JunoLab/Media.jl#11]
@MikeInnes Everything is broken on master because of this and because `DataFrames` now depends on this package. E.g.
```jl
julia> using DataFrames

julia> 1
Error showing value of type Int64:
ERROR: type TypeName has no field primary
Stacktrace:
 [1] display(::Media.DisplayHook, ::Int64) at /Users/andreasnoack/.julia/v0.6/Media/src/compat.jl:9
 [2] display(::Int64) at ./multimedia.jl:194
```
Defining `primarytype(x::Int) = Int` fixes it. I assume that is not correct but the package has no tests so I'm not sure how to fix this  in general.

**Comment by MikeInnes** [comment]
Should be fixed with https://github.com/JuliaLang/METADATA.jl/pull/7655

**Comment by andreasnoack** [comment]
Thanks for the prompt fix. I think it would make sense to avoid hooking into the type internals. They are not official API and therefore changes don't go through a deprecation period so breakages will always be hard.

**Comment by tkelman** [comment]
And being so imprecise with VERSION cutoffs means now anything that depends on this package is not easily bisectable with base Julia builds any older than a few weeks ago.
