### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/Media.jl#13]
For Julia v0.6, on release if a package does `using Juno`, then the `display` method breaks. This makes the REPL usage very wonky. However, it's fixed by checking out the master branch of this package. I was wondering a patch release could be put out as this will make debugging much easier!

**Comment by tlnagy** [comment]
We're in the process of getting Gadfly working on 0.6 and are running into this too. A tag would be great.

**Comment by tkelman** [comment]
> We're in the process of getting Gadfly working on 0.6 and are running into this too.

0.2.6 was tagged 2 weeks ago https://github.com/JuliaLang/METADATA.jl/pull/8511, whatever you're seeing might be new?

**Comment by pfitzseb** [comment]
Should be sufficiently tagged now...

**Comment by tlnagy** [comment]
Yeah, this was old version locally. My bad.
